### ISSUE TITLE
Refactor to be a GitHub Action instead of a workflow

### ISSUE THREAD

**Issue by ericcrosson-bitgo** [semantic-release-action/github-actions#10]
It's desirable to remove the workflow-only code (concurrency limits) which do not apply here. This was copy/pasta from when the semantic-release invocation was not a dry-run.

Also, the GitHub Action is the smallest reusable component, which describes this task. Using an action instead of a workflow leads to a simpler call-site (don't need multiple jobs, don't embed paths to the workflow)

**Comment by EricCrosson** [comment]
Wait, the concurrency limits do apply here! Was this issue meant to be opened on next-release-version?
